apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: flipkart-container
        image: jsarvabhowma/flipkart
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-svc
spec:
  type: NodePort
  selector:
    app: flipkart
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp-ns
spec:
  rules:
    - host: test.sarvanow.xyz
      http:
        paths:
          - path: /webapp
            backend:
              serviceName: flipkart-svc
              servicePort: 8080
